#!/bin/sh

prefix="$1"

sqlite3 tmp/types.sqlite "DELETE FROM result_curve_point WHERE curveid IN (SELECT id FROM result_curve WHERE corpuscode='check-$prefix' AND datasetcode='example')" || exit 1
sqlite3 tmp/types.sqlite "DELETE FROM result_curve WHERE corpuscode='check-$prefix' AND datasetcode='example'" || exit 1
sqlite3 tmp/types.sqlite "DELETE FROM result_p WHERE corpuscode='check-$prefix' AND datasetcode='example'" || exit 1
