#!/usr/bin/env python

import datetime
import re

copyright = 'Copyright (c)'
description = "Type and hapax accumulation curves"
author = "Jukka Suomela"
now = datetime.date.today()
version = now.isoformat()
year = now.year

with open('src/version.c', 'w') as f:
    f.write('''\
#include "version.h"

const char * const DESCRIPTION = "%s";
const char * const AUTHOR = "%s";
const char * const VERSION = "%s";
const char * const YEAR = "%d";
''' % (description, author, version, year))

with open('src/TypesVersion.py', 'w') as f:
    f.write('''\
DESCRIPTION = "%s"
AUTHOR = "%s"
VERSION = "%s"
YEAR = "%d"
''' % (description, author, version, year))

def filter(filename, fn):
    x = []
    with open(filename) as f:
        for l in f:
            x.append(fn(l.rstrip()))
    with open(filename, 'w') as f:
        for l in x:
            f.write(l + '\n')

def readme_filter(l):
    if copyright in l and author in l:
        return '%s %d %s.' % (copyright, year, author)
    else:
        return l

def web_filter(l):
    return re.sub(r'\bversion (\d\d\d\d-\d\d-\d\d)\b', 'version {}'.format(version), l)

filter('README.md', readme_filter)
filter('ui/index.html', web_filter)
