#!/usr/bin/env python

import datetime

description = "Type and hapax accumulation curves"
author = "Jukka Suomela"
now = datetime.date.today()
version = now.isoformat()
year1 = 2014
year2 = now.year

with open('src/version.c', 'w') as f:
    f.write('''\
#include "version.h"

const char * const DESCRIPTION = "%s";
const char * const AUTHOR = "%s";
const char * const VERSION = "%s";
const char * const YEAR = "%d-%d";
''' % (description, author, version, year1, year2))

with open('src/TypesVersion.py', 'w') as f:
    f.write('''\
DESCRIPTION = "%s"
AUTHOR = "%s"
VERSION = "%s"
YEAR = "%d-%d"
''' % (description, author, version, year1, year2))
