#!/usr/bin/python

import subprocess

description = "Type and hapax accumulation curves"
author = "Jukka Suomela"

gitver = subprocess.check_output(['git', 'describe']).rstrip()
gitdate = subprocess.check_output(['git', 'show', '-s', '--format=%ci', gitver]).rstrip()
gitdate = gitdate.split(' ')[0]
year = gitdate.split('-')[0]
version = "%s (%s)" % (gitver, gitdate)
print version

with open('src/version.c', 'w') as f:
    f.write('''\
#include "version.h"

const char * const DESCRIPTION = "%s";
const char * const AUTHOR = "%s";
const char * const VERSION = "%s";
const char * const YEAR = "%s";
''' % (description, author, version, year))

with open('src/TypesVersion.py', 'w') as f:
    f.write('''\
DESCRIPTION = "%s"
AUTHOR = "%s"
VERSION = "%s"
YEAR = "%s"
''' % (description, author, version, year))
